#!/usr/bin/env bash
# product/tests/smoke_install.sh
# Cross-platform installer smoke test (bash).
# Asserts a fresh install produces the expected files, config blocks,
# frontmatter, AGENTS.md (LF + no BOM), and that the installed rule equals
# the canonical fragment (install==update parity).
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
cd "$TMP"; mkdir .claude

# Simulate the submodule layout the scripts expect.
# install.sh resolves SOURCE_ROOT as "$SCRIPT_DIR/.." — so when we invoke the
# real repo script directly, SOURCE_ROOT becomes $REPO/product and templates +
# ai-rules are sourced from the real repo.  No copy needed; just run it.
bash "$REPO/product/scripts/install.sh" \
    --profile solo-developer \
    --ai-assistant claude-code \
    --force >/dev/null

# --- File existence ---
for f in logs/CHANGELOG.md logs/DEVLOG.md logs/STATE.md .logfile-config.yml \
         .claude/rules/log-file-maintenance.md; do
    test -f "$f" || { echo "FAIL: missing $f"; exit 1; }
done
test -d logs/adr || { echo "FAIL: missing logs/adr"; exit 1; }

# --- Config blocks ---
grep -q "^paths:" .logfile-config.yml      || { echo "FAIL: no paths block"; exit 1; }
grep -q "^token_targets:" .logfile-config.yml || { echo "FAIL: no token_targets block"; exit 1; }

# --- Frontmatter ---
head -1 logs/CHANGELOG.md | grep -q '^---$' || { echo "FAIL: CHANGELOG.md missing frontmatter"; exit 1; }

# Spec 2: AGENTS.md must land at project root.
test -f AGENTS.md || { echo "FAIL: AGENTS.md missing at project root"; exit 1; }

# Spec 4 §1: AGENTS.md is now a managed BLOCK. A fresh install wraps the
# canonical body in LFG:BEGIN/END markers, so the file no longer starts with
# the YAML frontmatter '---' — the BEGIN marker comes first, frontmatter is
# inside the block.
grep -q '<!-- LFG:BEGIN v' AGENTS.md || { echo "FAIL: AGENTS.md missing LFG:BEGIN marker"; exit 1; }
grep -q '<!-- LFG:END -->' AGENTS.md || { echo "FAIL: AGENTS.md missing LFG:END marker"; exit 1; }
# The canonical body (frontmatter + guidance) lives inside the block.
grep -q '^doc: AGENTS$' AGENTS.md || { echo "FAIL: AGENTS.md missing canonical body (doc: AGENTS)"; exit 1; }

# Spec 4 §3: NO root templates/ dir is created. Templates live only in
# .log-file-genius/product/templates/. Only logs/ gets template-derived files.
test -d templates && { echo "FAIL: install created a root templates/ dir (Spec 4 §3 regression)"; exit 1; } || true

# Spec 5 T4: installer seeds the incidents/ dir, a TEMPLATE.md (from
# INCIDENT_template.md), and a static empty-state README.md index placeholder.
test -d logs/incidents || { echo "FAIL: missing logs/incidents directory"; exit 1; }
test -f logs/incidents/TEMPLATE.md || { echo "FAIL: missing logs/incidents/TEMPLATE.md"; exit 1; }
grep -q '^# Incident Report:' logs/incidents/TEMPLATE.md \
    || { echo "FAIL: logs/incidents/TEMPLATE.md missing '# Incident Report:' heading"; exit 1; }
test -f logs/incidents/README.md || { echo "FAIL: missing logs/incidents/README.md"; exit 1; }
grep -qF '<!-- LFG:INCIDENTS-INDEX generated by lfg incidents-index -->' logs/incidents/README.md \
    || { echo "FAIL: logs/incidents/README.md missing incidents-index generated marker"; exit 1; }
grep -qF '_No incidents recorded yet._' logs/incidents/README.md \
    || { echo "FAIL: logs/incidents/README.md missing empty-state placeholder line"; exit 1; }
grep -q '^  incidents_dir:' .logfile-config.yml \
    || { echo "FAIL: .logfile-config.yml missing incidents_dir key"; exit 1; }

# Spec 2: AGENTS.md must be LF + no BOM (generator's documented contract).
if grep -q $'\r' AGENTS.md; then echo "FAIL: AGENTS.md has CRLF line endings"; exit 1; fi
head -c 3 AGENTS.md | grep -q $'\xEF\xBB\xBF' && { echo "FAIL: AGENTS.md has UTF-8 BOM"; exit 1; } || true

# Spec 4 §1: idempotent install — re-running the merge leaves AGENTS.md
# byte-identical (the merge short-circuits on an up-to-date file). We invoke
# the same entrypoint install.sh uses rather than re-running the whole script.
AGENTS_BEFORE_HASH="$(cksum < AGENTS.md)"
PYTHON_BIN=""
if command -v python3 >/dev/null 2>&1; then PYTHON_BIN="python3";
elif command -v python >/dev/null 2>&1; then PYTHON_BIN="python"; fi
if [ -n "$PYTHON_BIN" ]; then
    MERGE_OUT="$("$PYTHON_BIN" "$REPO/product/scripts/lfg.py" merge-agents-md --to "$TMP/AGENTS.md" 2>&1)"
    echo "$MERGE_OUT" | grep -qi 'up to date' || { echo "FAIL: second merge did not report up-to-date: $MERGE_OUT"; exit 1; }
    AGENTS_AFTER_HASH="$(cksum < AGENTS.md)"
    [ "$AGENTS_BEFORE_HASH" = "$AGENTS_AFTER_HASH" ] || { echo "FAIL: second merge changed AGENTS.md (not idempotent)"; exit 1; }
fi

# Spec 2: installed rule must equal the canonical fragment.
diff -q .claude/rules/log-file-maintenance.md \
    "$REPO/product/rules/log-file-maintenance.md" \
    || { echo "FAIL: installed rule != canonical fragment"; exit 1; }

if grep -q 'starter-packs' "$REPO/product/scripts/update.sh"; then
    echo "FAIL: update.sh still references starter-packs"; exit 1
fi

# --- Validator exits 0 on a fresh install ---
# Mirrors what CI runs (`validate-log-files.sh --verbose` after install). The
# STATE template legitimately warns (over budget until guidance is trimmed);
# in default mode warnings must be non-blocking — anything else breaks CI.
bash "$REPO/product/scripts/validate-log-files.sh" --verbose >/dev/null 2>&1 \
    || { echo "FAIL: validator exits non-zero on a clean install (CI regression)"; exit 1; }

echo "PASS (bash)"
