# product/tests/smoke_install.ps1
# Cross-platform installer smoke test (PowerShell).
# Asserts a fresh install produces the expected files, config blocks,
# frontmatter, AGENTS.md (LF + no BOM), and that the installed rule equals
# the canonical fragment (install==update parity).

$ErrorActionPreference = "Stop"

$REPO = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$TMP  = [System.IO.Path]::GetTempPath()
$TMP  = Join-Path $TMP ([System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Path $TMP | Out-Null

try {
    Set-Location $TMP
    New-Item -ItemType Directory -Path ".claude" | Out-Null

    # Run the real installer.  install.ps1 resolves SourceRoot as $ScriptDir/..
    # which equals $REPO/product when invoked via the real repo path, so
    # templates and ai-rules are sourced from the real repo.
    powershell -NoProfile -File "$REPO\product\scripts\install.ps1" `
        -Profile solo-developer `
        -AiAssistant claude-code `
        -Force | Out-Null

    # --- File existence ---
    $expectedFiles = @(
        "logs\CHANGELOG.md",
        "logs\DEVLOG.md",
        "logs\STATE.md",
        ".logfile-config.yml",
        ".claude\rules\log-file-maintenance.md"
    )
    foreach ($f in $expectedFiles) {
        if (-not (Test-Path $f)) {
            throw "FAIL: missing $f"
        }
    }
    if (-not (Test-Path "logs\adr" -PathType Container)) {
        throw "FAIL: missing logs\adr directory"
    }

    # --- Config blocks ---
    $configContent = Get-Content ".logfile-config.yml" -Raw
    if ($configContent -notmatch '(?m)^paths:') {
        throw "FAIL: no paths block in .logfile-config.yml"
    }
    if ($configContent -notmatch '(?m)^token_targets:') {
        throw "FAIL: no token_targets block in .logfile-config.yml"
    }

    # --- Frontmatter ---
    $firstLine = (Get-Content "logs\CHANGELOG.md" -TotalCount 1)
    if ($firstLine -ne "---") {
        throw "FAIL: CHANGELOG.md missing frontmatter (first line is '$firstLine')"
    }

    # Spec 2: AGENTS.md at project root.
    if (-not (Test-Path "AGENTS.md")) { Write-Host "FAIL: AGENTS.md missing at project root"; exit 1 }

    # Spec 4 §1: AGENTS.md is now a managed BLOCK. A fresh install wraps the
    # canonical body in LFG:BEGIN/END markers, so the file starts with the
    # BEGIN marker; the YAML frontmatter is INSIDE the block.
    $agentsText = [System.IO.File]::ReadAllText("$pwd\AGENTS.md")
    if ($agentsText -notmatch '<!-- LFG:BEGIN v') { Write-Host "FAIL: AGENTS.md missing LFG:BEGIN marker"; exit 1 }
    if ($agentsText -notmatch '<!-- LFG:END -->') { Write-Host "FAIL: AGENTS.md missing LFG:END marker"; exit 1 }
    if ($agentsText -notmatch '(?m)^doc: AGENTS$') { Write-Host "FAIL: AGENTS.md missing canonical body (doc: AGENTS)"; exit 1 }

    # Spec 4 §3: NO root templates/ dir is created.
    if (Test-Path "templates" -PathType Container) { Write-Host "FAIL: install created a root templates/ dir (Spec 4 §3 regression)"; exit 1 }

    # Spec 5 T4: installer seeds the incidents/ dir, a TEMPLATE.md (from
    # INCIDENT_template.md), and a static empty-state README.md index placeholder.
    if (-not (Test-Path "logs\incidents" -PathType Container)) { throw "FAIL: missing logs\incidents directory" }
    if (-not (Test-Path "logs\incidents\TEMPLATE.md")) { throw "FAIL: missing logs\incidents\TEMPLATE.md" }
    $incidentTemplate = Get-Content "logs\incidents\TEMPLATE.md" -Raw
    if ($incidentTemplate -notmatch '(?m)^# Incident Report:') {
        throw "FAIL: logs\incidents\TEMPLATE.md missing '# Incident Report:' heading"
    }
    if (-not (Test-Path "logs\incidents\README.md")) { throw "FAIL: missing logs\incidents\README.md" }
    $incidentsIndex = Get-Content "logs\incidents\README.md" -Raw
    if ($incidentsIndex -notmatch [regex]::Escape('<!-- LFG:INCIDENTS-INDEX generated by lfg incidents-index -->')) {
        throw "FAIL: logs\incidents\README.md missing incidents-index generated marker"
    }
    if ($incidentsIndex -notmatch [regex]::Escape('_No incidents recorded yet._')) {
        throw "FAIL: logs\incidents\README.md missing empty-state placeholder line"
    }
    if ($configContent -notmatch '(?m)^\s*incidents_dir:') {
        throw "FAIL: .logfile-config.yml missing incidents_dir key"
    }

    # Spec 5 T4: the seeded incidents README.md must be UTF-8 with NO BOM and LF
    # endings (byte-identical to incidents.build_index empty output). Same
    # byte-check pattern as AGENTS.md above.
    $incBytes = [System.IO.File]::ReadAllBytes("$pwd\logs\incidents\README.md")
    if ($incBytes.Length -ge 3 -and $incBytes[0] -eq 0xEF -and $incBytes[1] -eq 0xBB -and $incBytes[2] -eq 0xBF) {
        Write-Host "FAIL: logs\incidents\README.md has UTF-8 BOM"; exit 1
    }
    if ($incBytes -contains 0x0D) { Write-Host "FAIL: logs\incidents\README.md has CR (0x0D) bytes - CRLF line endings"; exit 1 }

    # Spec 2 / Spec 4: AGENTS.md must be UTF-8 with NO BOM and LF endings.
    # Assert by reading raw bytes: first 3 bytes != EF BB BF, and no 0x0D (CR).
    $bytes = [System.IO.File]::ReadAllBytes("$pwd\AGENTS.md")
    if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
        Write-Host "FAIL: AGENTS.md has UTF-8 BOM"; exit 1
    }
    if ($bytes -contains 0x0D) { Write-Host "FAIL: AGENTS.md has CR (0x0D) bytes - CRLF line endings"; exit 1 }

    # Spec 4 §1: idempotent install — re-running the merge leaves AGENTS.md
    # byte-identical (merge short-circuits on an up-to-date file).
    $before = [System.IO.File]::ReadAllBytes("$pwd\AGENTS.md")
    $py = $null
    if (Get-Command python -ErrorAction SilentlyContinue) { $py = "python" }
    elseif (Get-Command python3 -ErrorAction SilentlyContinue) { $py = "python3" }
    if ($py) {
        $mergeOut = & $py "$REPO\product\scripts\lfg.py" merge-agents-md --to "$pwd\AGENTS.md" 2>&1 | Out-String
        if ($mergeOut -notmatch 'up to date') { Write-Host "FAIL: second merge did not report up-to-date: $mergeOut"; exit 1 }
        $after = [System.IO.File]::ReadAllBytes("$pwd\AGENTS.md")
        if (-not ([System.Linq.Enumerable]::SequenceEqual($before, $after))) {
            Write-Host "FAIL: second merge changed AGENTS.md (not idempotent)"; exit 1
        }
    }

    # Spec 2: installed rule == canonical fragment.
    $installed = (Get-FileHash ".claude\rules\log-file-maintenance.md").Hash
    $canonical = (Get-FileHash "$REPO\product\rules\log-file-maintenance.md").Hash
    if ($installed -ne $canonical) { Write-Host "FAIL: installed rule != canonical fragment"; exit 1 }

    # update.sh must not reference starter-packs
    $updateSh = Get-Content "$REPO\product\scripts\update.sh" -Raw
    if ($updateSh -match 'starter-packs') {
        throw "FAIL: update.sh still references starter-packs"
    }

    Write-Host "PASS (powershell)"
}
finally {
    Set-Location $env:USERPROFILE
    Remove-Item -Recurse -Force $TMP -ErrorAction SilentlyContinue
}
