"""CLI-level tests for `lfg incidents-index` (Spec 5 §3, T3).

Mirrors test_lfg_archive.py / test_lfg_migrate_state.py: drive the real lfg.py
via subprocess against temp incident fixtures. The pure parse/render logic lives
in test_incidents.py; here we pin the CLI surface:
  - incidents-index on a dir with incident files -> README.md with markers + rows.
  - idempotent rerun -> "already up to date", byte-identical, no .bak.
  - --dir override resolves against cwd.
  - missing dir -> graceful exit 0 with message.
  - user-authored README (no marker) -> backed up to README.md.bak before
    overwrite; rerun (marker now present) -> overwritten in place, no new .bak.
  - stdout is ASCII (captured as ascii without decode errors).
"""
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LFG = ROOT / "product/scripts/lfg.py"

GENERATED_MARKER = "<!-- LFG:INCIDENTS-INDEX generated by lfg incidents-index -->"


def _run(args, cwd, stdin=""):
    return subprocess.run(
        [sys.executable, str(LFG)] + args,
        cwd=str(cwd), input=stdin, capture_output=True, text=True, encoding="utf-8",
    )


def _incident(date, title, severity, status):
    return textwrap.dedent(f"""\
        ---
        doc: INCIDENT
        ---

        # Incident Report: {title}

        **Date:** {date}
        **Severity:** {severity}
        **Status:** {status}

        ## Summary
        Something failed.
    """)


def _seed_incidents(tmp_path, subdir="logs/incidents"):
    """Create a config + an incidents dir with 3 realistic incident files."""
    (tmp_path / ".logfile-config.yml").write_text(textwrap.dedent("""
        paths:
          changelog: logs/CHANGELOG.md
          devlog: logs/DEVLOG.md
          state: logs/STATE.md
          incidents_dir: logs/incidents
    """), encoding="utf-8")
    inc = tmp_path / subdir
    inc.mkdir(parents=True, exist_ok=True)
    (inc / "2025-11-19-silent-write-failure.md").write_text(
        _incident("2025-11-19", "Silent write failure", "Medium",
                  "Open -- origin narrowed; fix not yet implemented"),
        encoding="utf-8")
    (inc / "2026-03-02-schema-drift.md").write_text(
        _incident("2026-03-02", "Schema drift", "High", "Resolved"),
        encoding="utf-8")
    (inc / "2026-05-10-token-overrun.md").write_text(
        _incident("2026-05-10", "Token budget overrun", "Low", "Mitigated"),
        encoding="utf-8")
    return inc


def test_incidents_index_creates_readme(tmp_path):
    inc = _seed_incidents(tmp_path)
    r = _run(["incidents-index"], cwd=tmp_path)
    assert r.returncode == 0, r.stderr
    assert "3 incident(s) indexed" in r.stdout

    readme = inc / "README.md"
    assert readme.is_file()
    content = readme.read_text(encoding="utf-8")
    assert GENERATED_MARKER in content
    assert "| Date | Severity | Status | Incident |" in content
    # All three titles linked, newest-first ordering.
    assert "[Schema Drift" not in content  # title comes from heading, not slug
    assert "Token budget overrun" in content
    assert content.index("token-overrun") < content.index("schema-drift") \
        < content.index("silent-write-failure")
    # No backup for a fresh write.
    assert not (inc / "README.md.bak").exists()


def test_incidents_index_idempotent_rerun(tmp_path):
    inc = _seed_incidents(tmp_path)
    r1 = _run(["incidents-index"], cwd=tmp_path)
    assert r1.returncode == 0, r1.stderr
    before = (inc / "README.md").read_bytes()

    r2 = _run(["incidents-index"], cwd=tmp_path)
    assert r2.returncode == 0, r2.stderr
    assert "already up to date" in r2.stdout
    # Byte-identical, no backup created.
    assert (inc / "README.md").read_bytes() == before
    assert not (inc / "README.md.bak").exists()


def test_incidents_index_dir_override(tmp_path):
    """--dir points at an arbitrary dir (not the config default)."""
    inc = _seed_incidents(tmp_path, subdir="custom/incidents")
    r = _run(["incidents-index", "--dir", "custom/incidents"], cwd=tmp_path)
    assert r.returncode == 0, r.stderr
    assert (inc / "README.md").is_file()
    # The config default dir was NOT created/touched.
    assert not (tmp_path / "logs" / "incidents").exists()


def test_incidents_index_missing_dir_graceful(tmp_path):
    (tmp_path / ".logfile-config.yml").write_text(textwrap.dedent("""
        paths:
          incidents_dir: logs/incidents
    """), encoding="utf-8")
    r = _run(["incidents-index"], cwd=tmp_path)
    assert r.returncode == 0, r.stderr
    assert "No incidents directory" in r.stdout
    assert "nothing to index" in r.stdout


def test_incidents_index_backs_up_user_readme(tmp_path):
    """A user-authored README (no marker) is backed up to README.md.bak before
    overwrite; a subsequent run (marker now present) overwrites in place."""
    inc = _seed_incidents(tmp_path)
    user_readme = "# My incidents notes\n\nHand-written, not generated by LFG.\n"
    (inc / "README.md").write_text(user_readme, encoding="utf-8")

    r1 = _run(["incidents-index"], cwd=tmp_path)
    assert r1.returncode == 0, r1.stderr
    assert "Backed up existing README.md" in r1.stdout

    bak = inc / "README.md.bak"
    assert bak.is_file()
    assert bak.read_text(encoding="utf-8") == user_readme
    # README is now our generated output.
    assert GENERATED_MARKER in (inc / "README.md").read_text(encoding="utf-8")

    # Modify an incident so the next run produces different content (forces a
    # real overwrite, not the idempotency short-circuit). The README already
    # carries the marker -> overwrite in place, NO new .bak.
    (inc / "2026-05-10-token-overrun.md").write_text(
        _incident("2026-05-10", "Token budget overrun", "Critical", "Open"),
        encoding="utf-8")
    r2 = _run(["incidents-index"], cwd=tmp_path)
    assert r2.returncode == 0, r2.stderr
    assert "Backed up" not in r2.stdout
    assert not (inc / "README.md.bak.2").exists()
    # Original backup untouched.
    assert bak.read_text(encoding="utf-8") == user_readme


def test_incidents_index_stdout_is_ascii(tmp_path):
    """Stdout must be ASCII-safe (Windows cp1252) — capture as ascii bytes."""
    _seed_incidents(tmp_path)
    r = subprocess.run(
        [sys.executable, str(LFG), "incidents-index"],
        cwd=str(tmp_path), capture_output=True,
    )
    assert r.returncode == 0, r.stderr.decode("utf-8", errors="replace")
    # Decoding stdout as strict ASCII must not raise.
    r.stdout.decode("ascii")
