"""Tolerant incident-report parsing + index rendering (Spec 5 §2).

Pure parse + render, stdlib only. `parse_incident` turns one standalone
incident-report `.md` into an `IncidentMeta` (never raising on a readable text
file); `build_index` globs a directory and renders a deterministic
`README.md` index table — the same input always yields byte-identical output,
so the CLI's idempotency short-circuit works.

Design highlights (validated against 5 real `schema writer 2` reports):
  - Date is FILENAME-authoritative (`YYYY-MM-DD-slug.md`); the header
    `**Date:**` / `**Date Discovered:**` field is only a fallback, parsed from
    common human formats to ISO. Unparseable header dates -> undated (sorts
    last, raw string shown).
  - Title from the first `# ` heading minus an `Incident Report:` / `Incident:`
    label; no heading -> a title derived from the filename slug.
  - Severity / Status via a tolerant `**<label>:**` regex; missing -> "—".
    Status is kept FULL in the dataclass; truncation happens only at render.

The `—` em-dash for empty fields only ever lands in the returned index STRING
(written to a UTF-8/LF file by the CLI), never in stdout. This module never
prints.
"""
from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

# Reuse the encoding-safe reader (utf-8-sig BOM strip + CRLF/CR -> LF). Sibling
# import (same pattern as archive.py); agents_merge is a valid module name.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from agents_merge import read_text_normalized

EMDASH = "—"  # — : only ever written to the index FILE, never stdout.
EMPTY_FIELD = EMDASH

GENERATED_MARKER = "<!-- LFG:INCIDENTS-INDEX generated by lfg incidents-index -->"

# Files that live in the incidents dir but are not incident reports.
_SKIP_NAMES = {"readme.md", "template.md"}

# A leading YYYY-MM-DD in a filename (authoritative date source).
_FILENAME_DATE_RE = re.compile(r"^(?P<date>\d{4}-\d{2}-\d{2})(?:[-_].*)?$")

# First `# ` heading (single hash, ATX style).
_HEADING_RE = re.compile(r"^#\s+(?P<title>.+?)\s*$", re.MULTILINE)

# Strip a leading `Incident Report:` / `Incident:` label (case-insensitive).
_TITLE_LABEL_RE = re.compile(r"^\s*incident(?:\s+report)?\s*:\s*", re.IGNORECASE)

# Header date field: `**Date:**` or `**Date Discovered:**`.
_DATE_FIELD_RE = re.compile(
    r"^\*\*\s*Date(?:\s+Discovered)?\s*:\*\*\s*(?P<val>.+?)\s*$",
    re.IGNORECASE | re.MULTILINE,
)

# Human date formats we try, in order, when parsing a header date to ISO.
_HUMAN_DATE_FORMATS = (
    "%Y-%m-%d",        # 2025-11-19
    "%B %d, %Y",       # November 19, 2025
    "%b %d, %Y",       # Nov 19, 2025
    "%d %B %Y",        # 19 November 2025
    "%d %b %Y",        # 19 Nov 2025
)

# Truncation caps for the table cells.
_STATUS_CAP = 55
_TITLE_CAP = 60

# Clause separators for status truncation (try each; take the head).
_STATUS_CLAUSE_SEPARATORS = (" — ", "; ", ";", " (")


@dataclass
class IncidentMeta:
    path: Path
    iso_date: str | None   # 'YYYY-MM-DD' or None if undated
    raw_date: str          # what to DISPLAY (ISO if known, else raw header, else '—')
    title: str
    severity: str          # free-text or '—'
    status: str            # full free-text or '—' (untruncated)


# --- Field extraction --------------------------------------------------------

def _field(content: str, label: str) -> str:
    """Return the value of a `**<label>:**` field, or '—' if missing.

    Tolerant: optional whitespace inside the bold markers, MULTILINE so it
    matches anywhere in the file, trailing hard-break spaces stripped.
    """
    pattern = re.compile(
        rf"^\*\*\s*{re.escape(label)}\s*:\*\*\s*(?P<val>.+?)\s*$",
        re.IGNORECASE | re.MULTILINE,
    )
    m = pattern.search(content)
    if not m:
        return EMPTY_FIELD
    val = m.group("val").strip()
    return val if val else EMPTY_FIELD


def _parse_human_date(raw: str) -> str | None:
    """Parse a human/ISO date string to 'YYYY-MM-DD', or None if unparseable."""
    candidate = raw.strip()
    if not candidate:
        return None
    for fmt in _HUMAN_DATE_FORMATS:
        try:
            return datetime.strptime(candidate, fmt).strftime("%Y-%m-%d")
        except ValueError:
            continue
    return None


def _title_from_slug(stem: str) -> str:
    """Derive a title from a filename stem: strip a leading YYYY-MM-DD-,
    replace -/_ with spaces, title-case."""
    slug = re.sub(r"^\d{4}-\d{2}-\d{2}[-_]?", "", stem)
    slug = slug.replace("-", " ").replace("_", " ").strip()
    if not slug:
        return stem
    return slug.title()


def parse_incident(path: Path) -> IncidentMeta:
    """Parse one incident-report file into IncidentMeta. Never raises on a
    readable text file — a non-incident `.md` still yields a best-effort row."""
    path = Path(path)
    content = read_text_normalized(path)

    # --- Date: filename-authoritative, else header fallback. ---
    iso_date: str | None
    raw_date: str
    fname_match = _FILENAME_DATE_RE.match(path.name)
    if fname_match:
        iso_date = fname_match.group("date")
        raw_date = iso_date
    else:
        date_field = _DATE_FIELD_RE.search(content)
        if date_field:
            raw_val = date_field.group("val").strip()
            parsed = _parse_human_date(raw_val)
            if parsed:
                iso_date = parsed
                raw_date = parsed
            else:
                iso_date = None
                raw_date = raw_val if raw_val else EMPTY_FIELD
        else:
            iso_date = None
            raw_date = EMPTY_FIELD

    # --- Title: first `# ` heading minus label, else filename slug. ---
    heading = _HEADING_RE.search(content)
    if heading:
        title = _TITLE_LABEL_RE.sub("", heading.group("title")).strip()
        if not title:
            title = _title_from_slug(path.stem)
    else:
        title = _title_from_slug(path.stem)

    severity = _field(content, "Severity")
    status = _field(content, "Status")

    return IncidentMeta(
        path=path,
        iso_date=iso_date,
        raw_date=raw_date,
        title=title,
        severity=severity,
        status=status,
    )


# --- Truncation --------------------------------------------------------------

def _cap(text: str, limit: int) -> str:
    """Cap text to `limit` chars, appending an ellipsis if truncated."""
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + "…"  # …


def _truncate_status(status: str) -> str:
    """First clause of a status (split on em-dash / `;` / ` (`), then capped."""
    if status == EMPTY_FIELD:
        return status
    head = status
    for sep in _STATUS_CLAUSE_SEPARATORS:
        if sep in head:
            head = head.split(sep, 1)[0].strip()
    return _cap(head, _STATUS_CAP)


def _escape_cell(text: str) -> str:
    """Escape pipes so a free-text value can't break the markdown table."""
    return text.replace("|", "\\|")


# --- Index rendering ---------------------------------------------------------

def _sort_incidents(incidents: list[IncidentMeta]) -> list[IncidentMeta]:
    """Newest-first: dated entries by (iso_date desc, filename asc), then
    undated entries (iso_date is None) LAST, ordered by filename.

    Dated and undated are sorted separately then concatenated, so undated never
    interleaves with dated. Each group is sorted deterministically by filename
    first (stable inner key), then dated is re-sorted by date descending — the
    stable sort preserves the filename tie-break within an identical date.
    """
    dated = [m for m in incidents if m.iso_date is not None]
    undated = [m for m in incidents if m.iso_date is None]
    dated.sort(key=lambda m: m.path.name)                # tie-break: filename asc
    dated.sort(key=lambda m: m.iso_date, reverse=True)   # primary: date desc
    undated.sort(key=lambda m: m.path.name)
    return dated + undated


def _frontmatter() -> str:
    return (
        "---\n"
        "doc: INCIDENTS-INDEX\n"
        "related:\n"
        "  changelog: ../CHANGELOG.md\n"
        "  devlog: ../DEVLOG.md\n"
        "  state: ../STATE.md\n"
        "---\n"
    )


def build_index(incidents_dir: Path) -> str:
    """Render the incidents index README.md content (deterministic string with a
    single trailing newline). Skips README.md / TEMPLATE.md case-insensitively."""
    incidents_dir = Path(incidents_dir)

    files = sorted(incidents_dir.glob("*.md"), key=lambda p: p.name)
    metas = [
        parse_incident(p)
        for p in files
        if p.name.lower() not in _SKIP_NAMES
    ]
    metas = _sort_incidents(metas)

    parts: list[str] = []
    parts.append(_frontmatter())
    parts.append("")
    parts.append(GENERATED_MARKER)
    parts.append("")
    parts.append("# Incident Reports")
    parts.append("")
    parts.append(
        "Standalone incident reports for this project, newest first. "
        "Generated by `lfg incidents-index`."
    )
    parts.append("")

    if not metas:
        parts.append("_No incidents recorded yet._")
        return "\n".join(parts) + "\n"

    parts.append("| Date | Severity | Status | Incident |")
    parts.append("|---|---|---|---|")
    for m in metas:
        date_cell = _escape_cell(m.raw_date)
        sev_cell = _escape_cell(m.severity)
        status_cell = _escape_cell(_truncate_status(m.status))
        title_cell = _escape_cell(_cap(m.title, _TITLE_CAP))
        link = f"[{title_cell}](./{m.path.name})"
        parts.append(f"| {date_cell} | {sev_cell} | {status_cell} | {link} |")

    return "\n".join(parts) + "\n"
